//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSCollection.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCollectionEntities : DbContext
    {
        public DBCollectionEntities()
            : base("name=DBCollectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Officer> Officer { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Year> Year { get; set; }
        public virtual DbSet<vw_PSITS> vw_PSITS { get; set; }
        public virtual DbSet<YearReport1> YearReport1 { get; set; }
        public virtual DbSet<vw_Admin> vw_Admin { get; set; }
    }
}
