//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSCollection.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Admin
    {
        public int id { get; set; }
        public string OFFICERS { get; set; }
        public string Student_Name { get; set; }
        public string Course { get; set; }
        public Nullable<int> yearLevel { get; set; }
    }
}
