//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSCollection.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearReport1
    {
        public string Student_Name { get; set; }
        public Nullable<int> Year_Level { get; set; }
        public Nullable<int> Total_1st_Year { get; set; }
        public Nullable<int> Total_2nd_Year { get; set; }
        public Nullable<int> Total_3rd_Year { get; set; }
        public Nullable<int> Total_4th_Year { get; set; }
    }
}
